# Generated by Django 3.2.23 on 2024-04-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='course',
        ),
    ]
