# Generated by Django 3.2.23 on 2024-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_remove_classgroup_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], default='100', max_length=10),
        ),
    ]
