# Generated by Django 3.2.23 on 2024-04-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0003_level_level_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='name',
        ),
    ]
