# Generated by Django 3.2.23 on 2024-04-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0004_remove_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='session_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Evening', 'Evening'), ('Weekend', 'Weekend')], default='Regular', max_length=10),
        ),
    ]
