# Generated by Django 3.2.23 on 2024-04-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0006_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_level',
        ),
    ]
