# Generated by Django 3.2.23 on 2024-04-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0007_remove_course_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Timetable.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
