# Generated by Django 3.2.23 on 2024-04-23 23:10

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0009_timetable_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(day='Monday', then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(day='Tuesday', then=django.db.models.expressions.Value(2)), django.db.models.expressions.When(day='Wednesday', then=django.db.models.expressions.Value(3)), django.db.models.expressions.When(day='Thursday', then=django.db.models.expressions.Value(4)), django.db.models.expressions.When(day='Friday', then=django.db.models.expressions.Value(5)), django.db.models.expressions.When(day='Saturday', then=django.db.models.expressions.Value(6)), django.db.models.expressions.When(day='Sunday', then=django.db.models.expressions.Value(7)), default=django.db.models.expressions.Value(8), output_field=models.IntegerField()), 'session_type']},
        ),
    ]
