# Generated by Django 3.2.23 on 2024-04-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0010_alter_timetable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
